stages:
  - build

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"
  tags:
    - dockerbuild
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    ## if arm64 builds are needed
    #- docker buildx install
    #- docker buildx create --use --name=multiarch --node=multiarch
    #- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    #- DOCKER_BUILDKIT=1 docker buildx build --push --platform linux/amd64,linux/arm64 -t $IMAGE_TAG .
    - DOCKER_BUILDKIT=1 docker build --push -t $IMAGE_TAG .
